# Veidnes apraksts
Description: This stack creates ECS infrastructure log group, cluster, service with application load balancer, task definition, container definition


# Izveidota CloudFormation saskarne, tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:             
      - Label:
          default: ECS properties
        Parameters: [ServiceName, ImageUri, TaskCount, ContainerPort, CpuUnits, Memory]

      - Label:
          default: Cross-stack reference
        Parameters: [NetworkStackName, SecurityGroupStackName, SecurityRoleStackName]


# Definētas ievadparamteru īpašības - tips, apraksts,  minimālais simbolu daudzums, atļautās vērtībās
#   1. ContainerPort - konteinera ports
#   2. TaskCount - uzdevumu jeb konteineru izpildījumu skaits
#   3. CpuUnits - CPU vienību skaits
#   4. Memory - RAM lielums
#   5. ServiceName - ECS servisa nosaukums
#   6. ImageUri - Docker imidža URI
#   7., 8., 9. SecurityRoleStack, NetworkStackName, SecurityGroupStackName - drošības lomu, grupu un tīklošanas steku nosaukumi
Parameters:       
  ContainerPort:    
    Type: Number
    Description: Container port to expose
    MinValue: 0  

  TaskCount:    
    Type: Number
    Description: Number of desired task count
    MinValue: 0  

  CpuUnits:
    Type: Number  
    Description: Number of CPU units used by the task      
    AllowedValues: [256, 512, 1024, 2048, 4096]

  Memory:
    Type: Number  
    Description: Amount of memory used by the task     
    AllowedValues: [512, 1024, 2048, 4096, 8192, 16384]  

  ServiceName:    
    Type: String
    Description: Name of your ECS service 
    MinLength: 1 

  ImageUri:    
    Type: String  
    Description: Docker image URI    
    MinLength: 1    

  SecurityRoleStackName:    
    Type: String 
    Description: Security role stack name
    MinLength: 1  

  NetworkStackName:    
    Type: String 
    Description: Network stack name
    MinLength: 1 

  SecurityGroupStackName:    
    Type: String 
    Description: Security group stack name
    MinLength: 1  


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni
#   1. EcsCluster - ECS klāsteris, nosaukums
#   2. LogGroup - žurnālu grupa
#   3. ApplicationLoadBalancer - ALB, publiski pieejams DNS, piesaistne ar ALB drošības grupu un izvietojums divos publiskos apakštīklos
#   4. TargetGroup - ALB mērķa grupa, izvietojums VPC tīklā, konteineru ports, atbalstāmais pieprasījumu protokols, status pārbaudes īpašības - intervāli, protokols
#   5. Listener - ALB uztvērējs, ports un protokols, mērķa grupa, pāradresācija, piesaistne ALB
#   6. TaskDefinition - ECS uzdevuma definīcija fails, izpildes tips, CPU un RAM vērtības, pieņemtas IAM lomas, tīklošanas režīms, konteinera definīcija
#   7. EcsService - atkarība no ALB resursiem, izpildes tips, izmantojamais ECS uzdevuma definīcijas fails, uzdevumu izpildes skaits, izvietojuma konfigurācijas, ALB piesaistnes, tīklošana konfigurācijas
Resources:    
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref AWS::StackName

  LogGroup:
    Type: AWS::Logs::LogGroup

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer      
    Properties:      
      Scheme: internet-facing    
      SecurityGroups: 
        - Fn::ImportValue: !Sub ${SecurityGroupStackName}:AlbSecurityGroupId        
      Subnets: 
        - Fn::ImportValue: !Sub ${NetworkStackName}:PublicSubnet1Id
        - Fn::ImportValue: !Sub ${NetworkStackName}:PublicSubnet2Id 

  TargetGroup:    
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:   
      Name: !Sub ${AWS::StackName}-TargetGroup  
      HealthCheckIntervalSeconds: 10
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      HealthCheckProtocol: HTTP
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: 
        Fn::ImportValue: !Sub ${NetworkStackName}:VpcId

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener    
    Properties:
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer      
  
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [FARGATE]
      Family: !Sub ${AWS::StackName}-Task-Definition 
      Cpu: !Ref CpuUnits
      Memory: !Ref Memory 
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub ${SecurityRoleStackName}:EcsServiceRoleArn   
      TaskRoleArn: 
        Fn::ImportValue: !Sub ${SecurityRoleStackName}:EcsServiceRoleArn              
      NetworkMode: awsvpc  
      ContainerDefinitions:
        - Name: !Sub ${ServiceName}-container
          Image: !Ref ImageUri
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: http
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: !Sub awslogs-${ServiceName}-service        

            

  EcsService:
    Type: AWS::ECS::Service 
    DependsOn: [ApplicationLoadBalancer, TargetGroup, Listener]     
    Properties:
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition 
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref TaskCount
      DeploymentConfiguration:        
        MinimumHealthyPercent: 100         
        MaximumPercent: 200 
      LoadBalancers:
        - ContainerName: !Sub ${ServiceName}-container
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: 
            - Fn::ImportValue: !Sub ${SecurityGroupStackName}:VpcTrafficSecurityGroupId          
          Subnets: 
            - Fn::ImportValue: !Sub ${NetworkStackName}:PrivateSubnet1Id
            - Fn::ImportValue: !Sub ${NetworkStackName}:PrivateSubnet2Id                          


# Definēti izveidoto resursu izvaddati un eksportētās vērtības
#   1. CodeCommitRepositoryUrl - apraksts, CodeCommit repozitorija klonējuma URL, eksportvērtības nosaukums
#   2. CodeCommitRepositoryName - apraksts, CodeCommit repozitorija nosaukums, eksportvērtības nosaukums
#   3. EcrRepositoryName - apraksts, ECR repozitorija nosaukums, eksportvērtības nosaukums
#   4. S3BucketName - apraksts, S3 krātuves nosaukums, eksportvērtības nosaukums
Outputs: 
  EcsClusterId:
    Description: The ECS Cluster ID 
    Value: !Ref EcsCluster
    Export:
      Name: !Sub ${AWS::StackName}:EcsClusterId

  EcsServiceArn:
    Description: The ECS service ARN 
    Value: !Ref EcsService
    Export:
      Name: !Sub ${AWS::StackName}:EcsServiceArn 

  EcsTaskName:
    Description: The ECS task name
    Value: !Sub ${ServiceName}-container
    Export:
      Name: !Sub ${AWS::StackName}:EcsTaskName

  AlbUrl:
    Description: The DNS for the application load balancer
    Value: !Sub http://${ApplicationLoadBalancer.DNSName}


      