# Veidnes apraksts
Description: This template creates RDS instance with installed MySQL database 


# Izveidota CloudFormation saskarne, tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: RDS instance MySQL database properties 
        Parameters: 
          - DbAllocatedStorage
          - DbClass
          - DbName
          - DbUsername
          - DbPassword 
          - MultiAzDeployment

      - Label:
          default: Cross-stack reference
        Parameters:          
          - NetworkStackName
          - SecurityGroupStackName


# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma, vērtību un struktūras ierobežojumi, atļautās vērtībās, ierobežojumu apraksts
#   1. DbAllocatedStorage - datubāzes izmērs
#   2. DbClass - RDS instances tips
#   3. DbName - datubāzes nosaukums
#   4. DbUser - datubāzes lietotājvārds
#   5. DbPassword - datubāzes lietotāja parole
#   6. MultiAz - iezvietot vairākās pieejamības zonās
#   7., 8. NetworkStackName, SecurityGroupStack - tīkla un drošības grupu steka nosaukums
Parameters:   
  DbAllocatedStorage:        
    Type: Number    
    Description: Enter the size of the database
    MinValue: 5    
    ConstraintDescription: Must be at least 5 GB 

  DbClass:  
    Type: String   
    Description: Database instance class    
    AllowedValues: [db.t2.micro, db.t2.xlarge, db.t2.2xlarge]

  DbName:
    Type: String    
    Description: Database name
    MinLength: 1
    MaxLength: 64    
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must contain only alphanumeric characters    

  DbUsername: 
    Type: String    
    Description: Ddatabase username
    MinLength: 1
    MaxLength: 16    
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters

  DbPassword: 
    NoEcho: true
    Description: Enter database password  
    Type: String    
    MinLength: 8
    MaxLength: 41
    ConstraintDescription: At least 8 symbols    

  MultiAzDeployment:    
    Type: String    
    Description: Enable Multi AZ deployment for RDS?
    AllowedValues: [true, false]  
  
  NetworkStackName:        
    Type: String    
    Description: Network stack name
    MinLength: 1    

  SecurityGroupStackName:        
    Type: String 
    Description: Security group stack name   
    MinLength: 1
    

# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni
#   Database - krātuves apjoms, RDS instances klase, datubāzes nosaukums, lietotājvārds un parole, pieejamības zonu izvietojums, drošības grupu piesaistne, izvietojums apakštīklos      
Resources: 
  Database: 
    Type: AWS::RDS::DBInstance 
    Properties: 
      AllocatedStorage: !Ref DbAllocatedStorage 
      DBInstanceClass: !Ref DbClass    
      DBName: !Ref DbName       
      Engine: MySQL 
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      MultiAZ: !Ref MultiAzDeployment
      PubliclyAccessible: false           
      VPCSecurityGroups: 
        - Fn::ImportValue: !Sub ${SecurityGroupStackName}:VpcTrafficSecurityGroupId
      DBSubnetGroupName: 
        Fn::ImportValue: !Sub ${NetworkStackName}:RdsSubnetGroupId

# Definēti izveidoto resursu izvaddati 
#   DatabaseEndpoint - apraksts, izveidotās datubāzes savienojuma galapunkts 
Outputs:     
  DatabaseEndpoint: 
    Description: Database endpoint    
    Value: !GetAtt Database.Endpoint.Address
   
