# Veidnes apraksts
Description: This template creates two security groups for application load balancers and traffic within VPC 


# Izveidota CloudFormation saskarne, tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Authorize inbound traffic CIDR range
        Parameters:          
          - AlbInboundCidr

      - Label:
          default: Cross-stack reference
        Parameters:          
          - NetworkStackName


# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma un struktūras ierobežojumi
#   1. NetworkStack - tīkla steka nosaukums
#   2. AlbInboundCidr - datuplūsmas avota atļauto IP adrešu diapozons
Parameters:
  AlbInboundCidr:
    Type: String
    Description: Authorize inbound traffic CIDR range (e.g. 0.0.0.0/0 for public access)
    MaxLength: 18
    MinLength: 9     
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x      

  NetworkStackName:        
    Type: String
    Description: Name of the network stack for export value usage
    MinLength: 1


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1.,2. VpcSecurityGroup, AlbSecurityGroup - drošības grupas nosaukums, apraksts, izvietojums VPC, ienākošās datuplūsmas noteikumi 
Resources:
  VpcTrafficSecurityGroup: 
    Type: AWS::EC2::SecurityGroup 
    Properties:     
      GroupName: !Sub ${AWS::StackName}:VpcTrafficSecurityGroup 
      GroupDescription: Allow traffic from within VPC 
      VpcId: 
        Fn::ImportValue: !Sub ${NetworkStackName}:VpcId
      SecurityGroupIngress:
        - IpProtocol: -1     
          CidrIp: 
            Fn::ImportValue: !Sub ${NetworkStackName}:VpcCidrBlock
           
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}:AlbSecurityGroup
      GroupDescription: Allow traffic to the application load balancer 
      VpcId: 
        Fn::ImportValue: !Sub ${NetworkStackName}:VpcId    
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref AlbInboundCidr    


# Definēti izveidoto resursu izvaddati un eksporta vērtības
#   1. VpcTrafficSecurityGroup - apraksts, VPC datuplūsmas drošības grupas resursa ID vērtība, eksportvērtības nosaukums 
#   2. AlbSecurityGroup - apraksts, ALB resursa drošības grupas resursa ID vērtība, eksportvērtības nosaukums 
Outputs:  
  VpcTrafficSecurityGroupId:
    Description: VPC traffic security grup ID
    Value: !Ref VpcTrafficSecurityGroup
    Export: 
      Name: !Sub ${AWS::StackName}:VpcTrafficSecurityGroupId
  
  AlbSecurityGroupId:
    Description: ALB traffic security grup ID
    Value: !Ref AlbSecurityGroup
    Export: 
      Name: !Sub ${AWS::StackName}:AlbSecurityGroupId
