Description: This template creates RDS instance with installed MySQL database 

# Tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: RDS instance MySQL database properties 
        Parameters: 
          - DbAllocatedStorage
          - DbClass
          - DbName
          - DbUser
          - DbPassword 

      - Label:
          default: Stack associations with CloudFormation stacks
        Parameters:          
          - NetworkStack
          - SecurityGroupStack


# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma, vērtību un struktūras ierobežojumi, atļautās vērtībās, ierobežojumu apraksts
#   1. DbAllocatedStorage - datubāzes izmērs
#   2. DbClass - RDS instances tips
#   3. DbName - datubāzes nosaukums
#   4. DbUser - datubāzes lietotājvārds
#   5. DbPassword - datubāzes lietotāja parole
#   6. NetworkStack - tīkla steka nosaukums
Parameters:   
  DbAllocatedStorage:        
    Type: Number    
    Description: Enter the size of the database (GB) 
    MinValue: 5    
    ConstraintDescription : Must be at least 5 GB 

  DbClass:  
    Type: String   
    Description: Database instance class    
    AllowedValues: [db.t2.xlarge, db.t2.2xlarge]
    ConstraintDescription: Must select a valid General purpose T2 database instance type      

  DbName:
    Type: String    
    MinLength: 1
    MaxLength: 64
    Description: Enter database name
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must contain only alphanumeric characters    

  DbUser: 
    Type: String    
    MinLength: 1
    MaxLength: 16
    Description: Enter database username
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters

  DbPassword: 
    NoEcho: true
    Type: String    
    MinLength: 8
    MaxLength: 41
    Description: Enter database password    
  
  NetworkStack:        
    Type: String    
    MinLength: 1
    Description: Name of the network stack for export value usage

  SecurityGroupStack:        
    Type: String    
    MinLength: 1
    Description: Name of the security group stack for export value usage


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1. Database - piešķirtais krātuves apjoms, RDS instances klase jeb tips, datubāzes nosaukums, programmatūra, lietotājvārds un parole, definēts vairāku pieejamības zonu izvietojums,
#      liegta publiska piekļuve, kartējums uz drošības grupu un VPC apakštīklu vērtībām
#   2. DatabaseSecurityGroup - drošības grupas nosaukums, apraksts, ienākošās datuplūsmas noteikumi un kartējums uz VPC vērtību
Resources: 
  Database: 
    Type: AWS::RDS::DBInstance 
    Properties: 
      AllocatedStorage: !Ref DbAllocatedStorage 
      DBInstanceClass: !Ref DbClass    
      DBName: !Ref DbName       
      Engine: MySQL 
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPassword
      MultiAZ: true
      PubliclyAccessible: false           
      VPCSecurityGroups: 
        - Fn::ImportValue: !Sub ${SecurityGroupStack}:VpcTrafficSecurityGroupId
      DBSubnetGroupName: 
        Fn::ImportValue: !Sub ${NetworkStack}:RdsSubnetGroupId

# Definēti izveidoto resursu izvaddati 
#   1. DatabaseEndpoint - apraksts, izveidotās datubāzes savienojuma galapunkta vērtība
Outputs:     
  DatabaseEndpoint: 
    Description: Database endpoint    
    Value: !GetAtt Database.Endpoint.Address
   
