Description: This template creates RDS instance with installed MySQL database and security group


# Tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: RDS instance MySQL database properties 
        Parameters:          
          - DatabaseName
          - DatabaseUser
          - DatabasePassword 

      - Label:
          default: RDS instance associations with other CloudFormation stacks
        Parameters:          
          - NetworkStack


# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma un struktūras ierobežojumi
#   1. StorageSize - datubāzes izmērs
#   2. NetworkStack - tīkla steka nosaukums
#   3. DatabaseName - datubāzes nosaukums
#   4. DatabaseUser - datubāzes lietotājvārds
#   5. DatabasePassword - datubāzes lietotāja parole
Parameters:   
  StorageSize:        
    Type: String
    MinLength: 1
    MaxLength: 3
    Description: Enter the size of the storage (GB) 

  NetworkStack:        
    Type: String
    MinLength: 1
    Description: Enter the name of your network stack that you want to associate with your DB instance.

  DatabaseName:
    Type: String
    MinLength: 1
    MaxLength: 30 
    AllowedPattern: "[a-zA-Z0-9]*" 
    ConstraintDescription: Must contain only alphanumeric characters.

  DatabaseUser: 
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

  DatabasePassword: 
    NoEcho: true
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must contain only alphanumeric characters


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1. Database - piešķirtais krātuves apjoms, RDS instances klase jeb tips, datubāzes nosaukums, programmatūra, lietotājvārds un parole, definēts vairāku pieejamības zonu izvietojums,
#      liegta publiska piekļuve, kartējums uz drošības grupu un VPC apakštīklu vērtībām
#   2. DatabaseSecurityGroup - drošības grupas nosaukums, apraksts, ienākošās datuplūsmas noteikumi un kartējums uz VPC vērtību
Resources: 
  Database: 
    Type: AWS::RDS::DBInstance 
    Properties: 
      AllocatedStorage: !Ref StorageSize 
      DBInstanceClass: db.t2.micro     
      DBName: !Ref DatabaseName       
      Engine: MySQL 
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      MultiAZ: true
      PubliclyAccessible: false           
      VPCSecurityGroups: [!Ref DatabaseSecurityGroup]     
      DBSubnetGroupName: 
        Fn::ImportValue: !Sub ${NetworkStack}:DBSubnetGroup
     
  DatabaseSecurityGroup: 
    Type: AWS::EC2::SecurityGroup 
    Properties:     
      GroupName: !Sub ${AWS::StackName} RDS Security Group 
      GroupDescription: 
        Fn::ImportValue: !Sub ${AWS::StackName} RDS Security Group, Allow traffic from within VPC ${NetworkStack}:VpcCidrBlock  
      SecurityGroupIngress:
        - CidrIp: 
            Fn::ImportValue: !Sub ${NetworkStack}:VpcCidrBlock
          IpProtocol: -1      
      VpcId: 
        Fn::ImportValue: !Sub ${NetworkStack}:VpcId


# Definēti izveidoto resursu izvaddati 
#   1. DatabaseEndpoint - apraksts, izveidotās datubāzes savienojuma galapunkta vērtība
Outputs:     
  DatabaseEndpoint: 
    Description: Database endpoint    
    Value: !GetAtt Database.Endpoint.Address
   
