Description: This stack deploys ECS Service and Codepipeline roles


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
# EcsServiceRole, EcsTaskRole, CodeBuildRole, CodePipelineRole - ECS servisa, uzdevuma, CodeBuild un CodePipeline lomas un attiecīgās piekļuves politikas dokumenti 
Resources:  
  EcsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole   
            Effect: Allow 
            Principal:
              Service: [ecs.amazonaws.com, ecs-tasks.amazonaws.com]                
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-EcsServiceRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*                 
                  - elasticloadbalancing:*                             
                  - logs:*
                  - ecr:*                   
                Resource: '*'   

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:      
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow        
            Principal:
              Service: [codebuild.amazonaws.com, codepipeline.amazonaws.com, codedeploy.amazonaws.com]     
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-CodePipelineRolePolicy
          PolicyDocument:            
            Statement:
              - Action:
                  - logs:*  
                  - s3:*
                  - ecs:*
                  - autoscaling:*               
                  - codecommit:*                 
                  - codebuild:* 
                  - ecr:*  
                  - iam:*                
                Effect: Allow
                Resource: '*'


# Definēti izveidoto resursu izvaddati un eksporta vērtības
#   1. EcsServiceRoleArn - apraksts, ECS servisa lomas resursa ARN vērtība un tās eksports
#   2. EcsTaskRoleArn - apraksts, ECS uzdevuma lomas resursa ARN vērtība un tās eksports
#   3. CodeBuildRoleArn - apraksts, CodeBuild lomas resursa ARN vērtība un tās eksports
#   4. CodePipelineRoleArn - apraksts, CodePipelineRoleArn lomas resursa ARN vērtība un tās eksports
Outputs: 
  EcsServiceRoleArn:
    Description: ECS Service IAM role Amazon Resource Name
    Value: !GetAtt EcsServiceRole.Arn
    Export: 
      Name: !Sub ${AWS::StackName}:EcsServiceRoleArn   
  
  CodePipelineRoleArn:
    Description: CodePipeline IAM role Amazon Resource Name
    Value: !GetAtt CodePipelineRole.Arn
    Export: 
      Name: !Sub ${AWS::StackName}:CodePipelineRoleArn

  
