# Veidnes apraksts
Description: This stack creates CodePipeline to build an ECS Fargate service from given CodeCommit repository and branch


# Izveidota CloudFormation saskarne, tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Pipeline properties 
        Parameters: [CodeCommitRepoName, CodeCommitRepoBranchName, S3BucketName]      
      
      - Label:
          default: Cross-stack reference
        Parameters: [SecurityRoleStackName, StorageStackName, ComputeStackTestName, ComputeStackProdName]


# Definētas ievadparamteru īpašības - tips, apraksts, minimālais simbolu daudzums
#   1. CodeCommitRepository - CodeCommit repozitorija nosaukums
#   2. CodeCommitRepoBranchName - CodeCommit repozitorija zara nosaukums
#   3. S3BucketName - S3 krātuves nosaukums
#   4. SecurityRoleStackName - drošības lomu steka nosaukums
#   5. StorageStackName - krātuvju steka nosaukums
#   6., 7. ComputeStackTestName, ComputeStackProdName - testa un produkcijas skaitļošanas steku nosaukumi
Parameters:       
  CodeCommitRepoName:
    Type: String
    Description: CodeCommit repository name 
    MinLength: 1  

  CodeCommitRepoBranchName:
    Description: CodeCommit repository branch name which to use in pipeline
    Type: String
    MinLength: 1   

  S3BucketName:
    Type: String
    Description: The S3 bucket for artifact storage
    MinLength: 1      

  SecurityRoleStackName:
    Type: String
    Description: IAM stack name 
    MinLength: 1   

  StorageStackName:
    Type: String
    Description: Storage stack name 
    MinLength: 1  

  ComputeStackTestName:    
    Type: String
    Description: Test compute stack name 
    MinLength: 1  

  ComputeStackProdName:    
    Type: String
    Description: Production compute stack name
    MinLength: 1     
    

# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni
#   1. CodeBuildProject - CodeBuild projekts, nosaukums, izmantotā IAM loma, artefaktu uzglabāšanas konfigurācija un projekta izguves vieta
#   2. CodePipelineProject - CodePipeline projekts, nosaukums, izmantotā IAM loma, posmu definīcijas
#   3. ArtifactStore - artefaktu uzglabāšanas vieta
Resources:  
  CodeBuildProject:
    Type: AWS::CodeBuild::Project   
    Properties:
      Name: !Sub CodeBuildProject-${AWS::StackName}-${CodeCommitRepoBranchName}    
      ServiceRole: 
        Fn::ImportValue: !Sub ${SecurityRoleStackName}:CodePipelineRoleArn      
      Environment:        
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-8  
        PrivilegedMode: true 
        EnvironmentVariables:          
          - Name: ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPOSITORY
            Type: PLAINTEXT
            Value: 
              Fn::ImportValue: !Sub ${StorageStackName}:EcrRepositoryName          
          - Name: TASK_NAME
            Type: PLAINTEXT
            Value: 
              Fn::ImportValue: !Sub ${ComputeStackTestName}:EcsTaskName 
      Artifacts:
        Type: CODEPIPELINE                 
      Source:        
        Type: CODEPIPELINE         
  
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline    
    Properties:
      Name: !Sub CodePipeline-${AWS::StackName}-${CodeCommitRepoBranchName} 
      RoleArn:    
        Fn::ImportValue: !Sub ${SecurityRoleStackName}:CodePipelineRoleArn         
      # Tiek definēti datu konveijerapstrādes līnijas posmi
      # Nosaukums, avota un izvaddatu artefakti, posma izpildes pakalpojums, nosaukums un tips, konfigurācijas
      Stages:       
        - Name: Source_Checkout
          Actions:
            - Name: SourceCheckoutAction
              OutputArtifacts:                
                - Name: SourceArtifact
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1               
                Provider: CodeCommit              
              Configuration:                
                BranchName: !Ref CodeCommitRepoBranchName
                RepositoryName: !Ref CodeCommitRepoName   

        - Name: Application_Build
          Actions:
            - Name: ApplicationBuildAction                           
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:                
                - Name: BuildArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild              
              Configuration:                
                ProjectName: !Ref CodeBuildProject
                PrimarySource: SourceArtifact

        - Name: Test_Cluster_Deployment
          Actions:
            - Name: TestClusterDeployAction   
              InputArtifacts:                
                - Name: BuildArtifact           
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ECS
              Configuration:
                ClusterName: 
                  Fn::ImportValue: !Sub ${ComputeStackTestName}:EcsClusterId                   
                ServiceName: 
                  Fn::ImportValue: !Sub ${ComputeStackTestName}:EcsServiceArn                                
                FileName: imagedefinitions.json          

        - Name: Production_Deployment_Approval
          Actions:
            - Name: ManualApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual

        - Name: Production_Cluster_Deployment
          Actions:
            - Name: ProdClusterDeployAction
              InputArtifacts:                
                - Name: BuildArtifact              
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ECS
              Configuration:
                ClusterName: 
                  Fn::ImportValue: !Sub ${ComputeStackProdName}:EcsClusterId                   
                ServiceName: 
                  Fn::ImportValue: !Sub ${ComputeStackProdName}:EcsServiceArn                         
                FileName: imagedefinitions.json 

      ArtifactStore:
        Type: S3
        Location: !Ref S3BucketName 
         

