# Veidnes apraksts
Description: This stack creates ECS service and Codepipeline roles


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1. ECS pakalpojuma loma un piekļuves dokuments (nosaukums definēts ar Sub funckiju atsaucoties uz steka nosaukumu)
#   2. CodePipeline pakalpojuma loma un piekļuves dokuments (nosaukums definēts ar Sub funckiju atsaucoties uz steka nosaukumu)
Resources:  
  EcsServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole   
            Effect: Allow 
            Principal:
              Service: [ecs.amazonaws.com, ecs-tasks.amazonaws.com]                
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-EcsServiceRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*                 
                  - elasticloadbalancing:*                             
                  - logs:*
                  - ecr:*                   
                Resource: '*'   

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:      
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow        
            Principal:
              Service: [codebuild.amazonaws.com, codepipeline.amazonaws.com]     
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-CodePipelineRolePolicy
          PolicyDocument:            
            Statement:
              - Action:
                  - logs:*  
                  - s3:*
                  - ecs:*
                  - autoscaling:*               
                  - codecommit:*                 
                  - codebuild:* 
                  - ecr:*  
                  - iam:*                
                Effect: Allow
                Resource: '*'


# Definēti izveidoto resursu izvaddati un eksporta vērtības
#   1. EcsServiceRoleArn - apraksts, ECS servisa lomas resursa ARN (izgūts ar GetAtt funckiju atsaucoties uz resursa atribūtu Arn), eksportvērtības nosaukums
#   2. CodePipelineRoleArn - apraksts, CodePipeline lomas resursa (izgūts ar GetAtt funckiju atsaucoties uz resursa atribūtu Arn), eksportvērtības nosaukums
Outputs: 
  EcsServiceRoleArn:
    Description: ECS Service IAM role Amazon Resource Name
    Value: !GetAtt EcsServiceRole.Arn
    Export: 
      Name: !Sub ${AWS::StackName}:EcsServiceRoleArn   
  
  CodePipelineRoleArn:
    Description: CodePipeline IAM role Amazon Resource Name
    Value: !GetAtt CodePipelineRole.Arn
    Export: 
      Name: !Sub ${AWS::StackName}:CodePipelineRoleArn

  
