Description: This template creates CodeCommit, ECR repositories and S3 bucket


# Tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Storage resources 
        Parameters:          
          - CodeCommitRepositoryName
          - CodeCommitRepositoryDescription
          - EcrRepositoryName    
 
          
# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma ierobežojumi
#   1. CodeCommitRepositoryName - CodeCommit repozitorija nosaukums
#   2. CodeCommitRepositoryDescription - CodeCommit repozitorija apraksts
#   3. EcrRepositoryName - ECR repozitorija nosaukums
Parameters:
  CodeCommitRepositoryName:
    Type: String
    Description: Name of your CodeCommit repository    
    MinLength: 1  

  CodeCommitRepositoryDescription:
    Type: String
    Description: Description of your CodeCommit repository    
    MinLength: 1    

  EcrRepositoryName:
    Type: String   
    Description: Name of your ECR repository    
    MinLength: 1   


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1. CodeCommitRepository- CodeCommit repozitorija apraksts un nosaukums
#   2. EcrRepository - ECR repozitorija nosaukums
#   3. S3Bucket - S3 krātuves izveides deklarācija
Resources:  
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: !Ref CodeCommitRepositoryDescription
      RepositoryName: !Ref CodeCommitRepositoryName
  
  EcrRepository:
    Type: AWS::ECR::Repository     
    Properties:       
      RepositoryName: !Ref EcrRepositoryName

  S3Bucket:
    Type: AWS::S3::Bucket
      

# Definēti izveidoto resursu izvaddati un eksportētās vērtības
#   1. CodeCommitRepositoryUrl - apraksts, CodeCommit repozitorija klonējuma URL vērtība un tās eksports
#   2. CodeCommitRepositoryName - apraksts, CodeCommit repozitorija nosaukuma vērtība un tās eksports
#   3. EcrRepositoryName - apraksts, ECR repozitorija nosaukuma vērtība un tās ekports
#   4. S3BucketName - apraksts, S3 krātuves nosaukums un tās eksports
Outputs:  
  CodeCommitRepositoryUrl:
    Description: CodeCommit repository URL
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp   
    Export: 
      Name: !Sub ${AWS::StackName}:CodeCommitRepositoryUrl

  CodeCommitRepositoryName:
    Description: CodeCommit repository name
    Value: !GetAtt CodeCommitRepository.Name   
    Export: 
      Name: !Sub ${AWS::StackName}:CodeCommitRepositoryName 

  EcrRepositoryName:
    Description: ECR repository name
    Value: !Sub ${EcrRepositoryName}   
    Export: 
      Name: !Sub ${AWS::StackName}:EcrRepositoryName

  S3BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
    Export: 
      Name: !Sub ${AWS::StackName}:S3BucketName 


  

     

