Description: This template creates CodeCommit, ECR repositories and S3 bucket


# Tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Storage resources 
        Parameters:          
          - CodeCommitRepositoryName
          - CodeCommitRepositoryDescription
          - EcrRepositoryName    
 
          
# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma ierobežojumi
Parameters:
  CodeCommitRepositoryName:
    Type: String
    Description: Name of your CodeCommit repository    
    MinLength: 1  

  CodeCommitRepositoryDescription:
    Type: String
    Description: Description of your CodeCommit repository    
    MinLength: 1    

  EcrRepositoryName:
    Type: String   
    Description: Name of your ECR repository    
    MinLength: 1   


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1. CodeCommit repozitorijs - apraksts un nosaukums
#   2. ECR repozitorijs - nosaukums
#   3. S3 krātuve 
Resources:  
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: !Ref CodeCommitRepositoryDescription
      RepositoryName: !Ref CodeCommitRepositoryName
  
  ECRRepository:
    Type: AWS::ECR::Repository     
    Properties:       
      RepositoryName: !Ref EcrRepositoryName

  S3Bucket:
    Type: AWS::S3::Bucket
      

# Definēti izveidoto resursu izvaddati un eksportētās vērtības
#   1. CodeCommitRepositoryUrl 
#   2. CodeCommitRepositoryName
#   3. S3BucketName
Outputs:  
  CodeCommitRepositoryUrl:
    Description: CodeCommit repository URL
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp   
    Export: 
      Name: !Sub ${AWS::StackName}:CodeCommitRepositoryUrl

  CodeCommitRepositoryName:
    Description: CodeCommit repository name
    Value: !GetAtt CodeCommitRepository.Name   
    Export: 
      Name: !Sub ${AWS::StackName}:CodeCommitRepositoryName 

  EcrRepositoryName:
    Description: ECR repository name
    Value: !Sub ${EcrRepositoryName}   
    Export: 
      Name: !Sub ${AWS::StackName}:EcrRepositoryName

  S3BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
    Export: 
      Name: !Sub ${AWS::StackName}:S3BucketName 


  

     

