# Veidnes apraksts
Description: This template creates CodeCommit, ECR repositories and S3 bucket


# Izveidota CloudFormation saskarne, tiek grupēta ievadparametru sekcija
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Storage resources 
        Parameters:          
          - CodeCommitRepoName
          - CodeCommitRepoDescr
          - EcrRepoName    
 
          
# Definēti ievadparamteri, to tips, apraksts, simbolu daudzuma ierobežojumi
#   1. CodeCommitRepoName - CodeCommit repozitorija nosaukums
#   2. CodeCommitRepoDescription - CodeCommit repozitorija apraksts
#   3. EcrRepoName - ECR repozitorija nosaukums
Parameters:
  CodeCommitRepoName:
    Type: String
    Description: Name of your CodeCommit repository    
    MinLength: 1  

  CodeCommitRepoDescr:
    Type: String
    Description: Description of your CodeCommit repository    
    MinLength: 1    

  EcrRepoName:
    Type: String   
    Description: Name of your ECR repository    
    MinLength: 1   


# Definēti visi resursi un to īpašības, kas tiks izveidoti, izpildot šo veidni:
#   1. CodeCommitRepository- CodeCommit repozitorija apraksts un nosaukums
#   2. EcrRepository - ECR repozitorija nosaukums
#   3. S3Bucket - S3 krātuves izveides deklarācija
Resources:  
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: !Ref CodeCommitRepoDescr
      RepositoryName: !Ref CodeCommitRepoName
  
  EcrRepository:
    Type: AWS::ECR::Repository    
    Properties:       
      RepositoryName: !Ref EcrRepoName

  S3Bucket:
    Type: AWS::S3::Bucket
      

# Definēti izveidoto resursu izvaddati un eksportētās vērtības
#   1. CodeCommitRepositoryUrl - apraksts, CodeCommit repozitorija klonējuma URL (izgūts ar GetAtt funckiju atsaucoties uz resursa atribūtu CodeCommitRepositoryUrl), eksportvērtības nosaukums
#   2. CodeCommitRepositoryName - apraksts, CodeCommit repozitorija nosaukums (izgūts ar GetAtt funckiju atsaucoties uz resursa atribūtu Name), eksportvērtības nosaukums
#   3. EcrRepositoryName - apraksts, ECR repozitorija nosaukums (izgūts ar Ref funckiju atsaucoties uz veidnes ievadparamtetra EcrRepoName vērtību), eksportvērtības nosaukums
#   4. S3BucketName - apraksts, S3 krātuves nosaukums (izgūts ar Ref funckiju atsaucoties uz resursa ID), eksportvērtības nosaukums
Outputs:  
  CodeCommitRepositoryUrl:
    Description: CodeCommit repository clone URL
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp   
    Export: 
      Name: !Sub ${AWS::StackName}:CodeCommitRepositoryUrl

  CodeCommitRepositoryName:
    Description: CodeCommit repository name
    Value: !GetAtt CodeCommitRepository.Name   
    Export: 
      Name: !Sub ${AWS::StackName}:CodeCommitRepositoryName 

  EcrRepositoryName:
    Description: ECR repository name
    Value: !Ref EcrRepoName 
    Export: 
      Name: !Sub ${AWS::StackName}:EcrRepositoryName

  S3BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
    Export: 
      Name: !Sub ${AWS::StackName}:S3BucketName 


  

     

