Parameters: # Ievadparametru sadala https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

  CodeCommitRepoName: # Ievadparametrs, nepieciesams noradit koda glabatuves vietas nosaukumu, kura izveidota manuali ieprieks
    Type: String 

  ServerStack: # Ievadparametrs, nepieciesams noradit ieprieks izveidotu resursu grupas nosaukumu, uz kuras resursiem tiks izvietota aplikacija, jeb darbosies automatiska izvietosana
    Type: String
    MinLength: 1
    MaxLength: 255 # Definets ievadparametra simbolu skaita limits
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$" # Defineti ievadparametra struktura, jeb atlautie simboli
  SecurityStack: # Ievadparametrs, nepieciesams noradit ieprieks izveidotu resursu grupas nosaukumu, uz kuras resursiem tiks izvietota aplikacija, jeb darbosies automatiska izvietosana
    Type: String
    MinLength: 1
    MaxLength: 255 # Definets ievadparametra simbolu skaita limits
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$" # Defineti ievadparametra struktura, jeb atlautie simboli

Resources: # Resursu definesanas sadala  
  
  CodeBuildProject: # Deklareta jauna "AWS" resursa, jeb projekta izveide, kurs atbildes par koda kompilaciju
    Type: AWS::CodeBuild::Project # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
    #DependsOn: CodeBuildRole # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html
    Properties:
      Name: !Join ["-",[ !Ref "AWS::StackName", "BuildProject"]] # Definets nosaukums izmantojot "AWS" ieprieks definetu funkciju "Join" - savienojot sis resursu grupas nosaukumu ar vardu "BuildProject".       
      Artifacts:
        Type: NO_ARTIFACTS
      Description: "Build application"    
      Environment: # Definetas sekojosas koda kompilacijas vides ipasibas. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html
        ComputeType: BUILD_GENERAL1_SMALL # Definets kompilacijas vides tips. 
        Image: aws/codebuild/java:openjdk-8 # Definets "AWS" ieprieks definets un uzglabats "Docker" imidzs, kurs izveidots izoletu konteinera vidi, kura tiks veikta koda kompilacija
        Type: LINUX_CONTAINER 
      ServiceRole:
         Fn::ImportValue: !Join [":", [!Ref "SecurityStack", CodeBuildRole]]  # Atsauce uz lomu, jeb atlauju kompumu, kas tiks pieskirta sim projektam
      Source: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html
        Type: CODECOMMIT
        Location: !Join
          - ''
          - - 'https://git-codecommit.'
            - !Ref 'AWS::Region'
            - '.amazonaws.com/v1/repos/'
            - !Ref 'CodeCommitRepoName'

  CodeDeployApplication:
    Properties:
      ApplicationName: !Join ["-",[ !Ref "AWS::StackName", "DeploymentApplication"]] # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-application.html
    Type: "AWS::CodeDeploy::Application"   

  DeploymentGroup:
    Type: "AWS::CodeDeploy::DeploymentGroup" # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html    
    Properties:
      ApplicationName: !Ref CodeDeployApplication      
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentGroupName: !Join ["-",[ !Ref "AWS::StackName", "DeploymentGroup"]] # Definets nosaukums izmantojot "AWS" ieprieks definetu funkciju "Join" - savienojot sis resursu grupas nosaukumu ar vardu "DeploymentGroup".
      ServiceRoleArn: 
        Fn::ImportValue: !Join [":", [!Ref "SecurityStack", CodeDeployRole]] 
      AutoScalingGroups: 
        - Fn::ImportValue: !Join [":", [!Ref "ServerStack", AutoScalingGroup]] 

  Pipeline: # Deklareta jauna "AWS" resursa izveide, kas nodrosinas nepartrauktu koda kompilaciju un izvietosanu
    Type: "AWS::CodePipeline::Pipeline" # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
    Properties:
      Name: !Join ["-",[ !Ref "AWS::StackName", "Pipeline"]] # Definets nosaukums izmantojot "AWS" ieprieks definetu funkciju "Join" - savienojot sis resursu grupas nosaukumu ar vardu "Pipeline".
      ArtifactStore: # Definets, kur tiks glabati "Pipeline" izveidotie artifakti.
        Location: !Ref "ArtifactsBucket" # Atsauce uz definetu glabatuvi.
        Type: S3 # Artefaktu glabatuves resursa tips. 
      RoleArn: 
        Fn::ImportValue: !Join [":", [!Ref "SecurityStack", CodePipelineRole]]  # Loma, jeb atlauju kopums, kas tiks asociets ar so "Pipeline", lai ta varetu izpildit nepieciesamas darbibas. Izmantota "AWS" ieprieks definetu funkcija "GetAtt".
      Stages: # Definetas "Pipeline" fazes. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages.html
        - Name: Source # Pirmas Fazes nosaukums
          Actions: # Definetas fazes darbibas. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html
          - InputArtifacts: [] # Saja pirmaja faze nebus ievaddatu, jeb artifaktu
            Name: "ScmCheckout" 
            ActionTypeId: # Definetu nepieciesamie fazes darbibas atributi. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions-actiontypeid.html
              Category: Source
              Owner: AWS
              Provider: CodeCommit # Definets "AWS" resursa nosaukums, kurs satures izcelsmes datus saja faze 
              Version: '1'
            OutputArtifacts: [Name: "SourceOutputArtifact"] # Defineti izvades artifakti, kas tiks izveidoti sis darbibas rezultata
            Configuration: # Defineti nepieciesamie konfiguracijas atributi.
              RepositoryName: "Petclinic" # Noradits koda glabatuves nosaukums, kam jabut jau ieprieks izveidotam manuali.
              BranchName: "master" # Noradits koda glabatuves "zars", jeb noteikta datu satura versija, kas jauzskata par avotu saj fazei.
              PollForSourceChanges: true # Definets, ka "Pipeline" resursam javeic sekosana koda glabatuves izmainam.              
        - Name: Build # Otras Fazes nosaukums
          Actions:
          - InputArtifacts: [Name: "SourceOutputArtifact"] # Saja otraja faze tiks izmantoti ievaddati, kas tika izveidoti pirmas fazes izpildes rezultata.
            Name: "Build" 
            ActionTypeId: # Definetu nepieciesamie fazes darbibas atributi. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions-actiontypeid.html
              Category: Build 
              Owner: AWS
              Provider: CodeBuild # Definets "AWS" resursa nosaukums, kurs izpildis noteiktas darbibas, lai realizetu sis fazes uzdevumus.
              Version: '1'
            OutputArtifacts: [Name: "BuildOutputArtifact"] # Defineti izvades artifakti, kas tiks izveidoti sis darbibas rezultata           
            Configuration:
              ProjectName: !Ref CodeBuildProject # Atsauce uz izveidotu resursu, jeb projektu, kurs veiks koda kompilaciju
        - Name: Deploy
          Actions:
          - InputArtifacts: [Name: "BuildOutputArtifact"] # Saja tresaja faze tiks izmantoti artefakti, kas tika izveidoti otras fazes izpildes rezultata.
            Name: "Deploy"
            ActionTypeId: # Definetu nepieciesamie fazes darbibas atributi. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions-actiontypeid.html
              Category: "Deploy"
              Owner: AWS
              Version: '1'
              Provider: CodeDeploy # Definets "AWS" resursa nosaukums, kurs nodrosinas aplikacijas izvietosanu
            OutputArtifacts: [] # Saja tresaja - nosledzosaja faze netiks izveidoti izvades artefakti
            Configuration:
              ApplicationName: !Ref CodeDeployApplication # Atsauce uz izveidotu resursu, jeb projektu, kurs veiks aplikacijas izvietosanu uz virtualajiem serveriem
              DeploymentGroupName: !Ref DeploymentGroup # Atsauce uz projektu, kura noraditas merka virtualie serveri uz kuriem jaizvieto si aplikacija

  ArtifactsBucket: 
    Type: "AWS::S3::Bucket" # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
    DeletionPolicy: Delete
    Description: S3 bucket for AWS CodePipeline and CodeBuild artifacts
    Properties:      
      VersioningConfiguration:
        Status: Enabled

# https://github.com/aws-samples/aws-codebuild-samples/tree/master/cloudformation
# https://github.com/stelligent/aws-codedeploy-sample-tomcat/blob/master/pipeline.yml